const kanaToRomaji: Array<[string, string]> = [
  ["あ", "a"],
  ["い", "i"],
  ["いぇ", "ye"],
  ["う", "u"],
  ["わ", "wa"],
  ["うぁ", "wa"],
  ["うぁ", "ua"],
  ["うぃ", "wi"],
  ["うぃ", "ui"],
  ["うぇ", "we"],
  ["え", "e"],
  ["お", "o"],
  ["か", "ka"],
  ["が", "ga"],
  ["き", "ki"],
  ["きぇ", "kye"],
  ["きゃ", "kya"],
  ["きゅ", "kyu"],
  ["きょ", "kyo"],
  ["ぎ", "gi"],
  ["ぎぇ", "gye"],
  ["ぎゃ", "gya"],
  ["ぎゅ", "gyu"],
  ["ぎょ", "gyo"],
  ["く", "ku"],
  ["くぁ", "kua"],
  ["くぃ", "kui"],
  ["くぇ", "kue"],
  ["くぉ", "kuo"],
  ["ぐ", "gu"],
  ["ぐぁ", "gua"],
  ["ぐぃ", "gui"],
  ["ぐぇ", "gue"],
  ["ぐぉ", "guo"],
  ["け", "ke"],
  ["げ", "ge"],
  ["こ", "ko"],
  ["ご", "go"],
  ["さ", "sa"],
  ["ざ", "za"],
  ["し", "shi"],
  ["し", "si"],
  ["しぇ", "she"],
  ["しぇ", "sye"],
  ["しゃ", "sha"],
  ["しゃ", "sya"],
  ["しゅ", "shu"],
  ["しゅ", "syu"],
  ["しょ", "sho"],
  ["しょ", "syo"],
  ["じ", "ji"],
  ["じぇ", "je"],
  ["じぇ", "jye"],
  ["じゃ", "ja"],
  ["じゃ", "jya"],
  ["じゅ", "ju"],
  ["じゅ", "jyu"],
  ["じょ", "jo"],
  ["じょ", "jyo"],
  ["す", "su"],
  ["すぁ", "sua"],
  ["すぃ", "sui"],
  ["すぇ", "sue"],
  ["すぉ", "suo"],
  ["ず", "zu"],
  ["ずぁ", "zua"],
  ["ずぃ", "zui"],
  ["ずぇ", "zue"],
  ["ずぉ", "zuo"],
  ["せ", "se"],
  ["ぜ", "ze"],
  ["そ", "so"],
  ["ぞ", "zo"],
  ["た", "ta"],
  ["だ", "da"],
  ["ち", "chi"],
  ["ちぇ", "che"],
  ["ちゃ", "cha"],
  ["ちゅ", "chu"],
  ["ちょ", "cho"],
  ["つ", "tsu"],
  ["つ", "tu"],
  ["つぁ", "tsa"],
  ["つぁ", "tua"],
  ["つぃ", "tsi"],
  ["つぃ", "tui"],
  ["つぇ", "tse"],
  ["つぇ", "tue"],
  ["つぉ", "tso"],
  ["つぉ", "tuo"],
  ["て", "te"],
  ["てぃ", "ti"],
  ["てゅ", "tyu"],
  ["で", "de"],
  ["でぃ", "di"],
  ["でゅ", "dyu"],
  ["と", "to"],
  ["とぅ", "tu"],
  ["とぅ", "twu"],
  ["ど", "do"],
  ["どぅ", "du"],
  ["どぅ", "dwu"],
  ["な", "na"],
  ["に", "ni"],
  ["にぇ", "nye"],
  ["にゃ", "nya"],
  ["にゅ", "nyu"],
  ["にょ", "nyo"],
  ["ぬ", "nu"],
  ["ぬぁ", "nua"],
  ["ぬぃ", "nui"],
  ["ぬぇ", "nue"],
  ["ぬぉ", "nuo"],
  ["ね", "ne"],
  ["の", "no"],
  ["は", "ha"],
  ["ば", "ba"],
  ["ぱ", "pa"],
  ["ひ", "hi"],
  ["ひぇ", "hye"],
  ["ひゃ", "hya"],
  ["ひゅ", "hyu"],
  ["ひょ", "hyo"],
  ["び", "bi"],
  ["びぇ", "bye"],
  ["びゃ", "bya"],
  ["びゅ", "byu"],
  ["びょ", "byo"],
  ["ぴ", "pi"],
  ["ぴぇ", "pye"],
  ["ぴゃ", "pya"],
  ["ぴゅ", "pyu"],
  ["ぴょ", "pyo"],
  ["ふ", "fu"],
  ["ふぁ", "fa"],
  ["ふぃ", "fi"],
  ["ふぇ", "fe"],
  ["ふぉ", "fo"],
  ["ぶ", "bu"],
  ["ぶぁ", "bua"],
  ["ぶぃ", "bui"],
  ["ぶぇ", "bue"],
  ["ぶぉ", "buo"],
  ["ぷ", "pu"],
  ["ぷぁ", "pua"],
  ["ぷぃ", "pui"],
  ["ぷぇ", "pue"],
  ["ぷぉ", "puo"],
  ["へ", "he"],
  ["べ", "be"],
  ["ぺ", "pe"],
  ["ほ", "ho"],
  ["ぼ", "bo"],
  ["ぽ", "po"],
  ["ま", "ma"],
  ["み", "mi"],
  ["みぇ", "mye"],
  ["みゃ", "mya"],
  ["みゅ", "myu"],
  ["みょ", "myo"],
  ["む", "mu"],
  ["むぁ", "mua"],
  ["むぃ", "mui"],
  ["むぇ", "mue"],
  ["むぉ", "muo"],
  ["め", "me"],
  ["も", "mo"],
  ["や", "ya"],
  ["ゆ", "yu"],
  ["よ", "yo"],
  ["ら", "ra"],
  ["り", "ri"],
  ["りぇ", "rye"],
  ["りゃ", "rya"],
  ["りゅ", "ryu"],
  ["りょ", "ryo"],
  ["る", "ru"],
  ["るぁ", "rua"],
  ["るぃ", "rui"],
  ["るぇ", "rue"],
  ["るぉ", "ruo"],
  ["れ", "re"],
  ["ろ", "ro"],
  ["わ", "wa"],
  ["を", "o"],
  ["うぉ", "wo"],
  ["ん", "n"],
  ["ー", "-"],
];

export const kanas = kanaToRomaji.map((it) => it[0]);
export const romajis = kanaToRomaji.map((it) => it[1]);

export function findKanaIndex(text: string): number | null {
  const index = kanas.indexOf(text);
  return index >= 0 ? index : null;
}

export function findRomajiIndex(text: string): number | null {
  const index = romajis.indexOf(text);
  return index >= 0 ? index : null;
}

export function isKana(text: string): boolean {
  return findKanaIndex(text) != null;
}

export function isRomaji(text: string): boolean {
  return findRomajiIndex(text) != null;
}

export function findVowelKana(kana: string): string | null {
  const romaji = kanaToRomaji.find((it) => it[0] === kana)?.[1];
  if (!romaji) return null;
  const vowelRomaji = romaji.slice(-1);
  return kanaToRomaji.find((it) => it[1] === vowelRomaji)?.[0] ?? null;
}

export function toRomaji(text: string): string {
  return kanaToRomaji.find((it) => it[0] === text)?.[1] ?? text;
}

export function toKana(text: string): string {
  return kanaToRomaji.find((it) => it[1] === text)?.[0] ?? text;
}
